const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

const repoRoot = path.resolve(__dirname, "..");

function readRepoFile(...parts) {
  return fs.readFileSync(path.join(repoRoot, ...parts), "utf8");
}

test("rect area selection is loaded and wired to the side toolbar", () => {
  const indexSource = readRepoFile("index.html");
  const appSource = readRepoFile("js", "app.js");
  const toolbarSource = readRepoFile("js", "vertical-toolbar.js");
  const topToolbarSource = readRepoFile("js", "top-toolbar.js");
  const selectionSource = readRepoFile("js", "area-selection-tool.js");
  const topToolbarCss = readRepoFile("css", "top-toolbar.css");
  const layoutSource = readRepoFile("css", "layout.css");

  assert.match(indexSource, /js\/area-selection-tool\.js/);
  assert.match(indexSource, /js\/selection-region\.js[\s\S]*js\/area-selection-tool\.js/);
  assert.match(appSource, /initAreaSelectionTool\?\.\(\)/);
  assert.match(toolbarSource, /data-tool-mode="selection-rect"/);
  assert.match(toolbarSource, /data-tool-mode="selection-circle"/);
  assert.match(toolbarSource, /data-tool-mode="selection-lasso"/);
  assert.match(toolbarSource, /data-tool-mode="selection-polygon-lasso"/);
  assert.match(toolbarSource, /data-tool-mode="selection-color-range"/);
  assert.match(toolbarSource, /POLYGON LASSO/);
  assert.match(toolbarSource, /COLOR RANGE/);
  assert.match(selectionSource, /const RECT_TOOL_MODE = "selection-rect"/);
  assert.match(selectionSource, /const CIRCLE_TOOL_MODE = "selection-circle"/);
  assert.match(selectionSource, /const LASSO_TOOL_MODE = "selection-lasso"/);
  assert.match(selectionSource, /const POLYGON_LASSO_TOOL_MODE = "selection-polygon-lasso"/);
  assert.match(selectionSource, /const COLOR_RANGE_TOOL_MODE = "selection-color-range"/);
  assert.match(selectionSource, /const DEFAULT_COLOR_RANGE_TOLERANCE = 48/);
  assert.match(selectionSource, /const LASSO_MIN_POINTS = 3/);
  assert.match(selectionSource, /const POLYGON_LASSO_CLOSE_DISTANCE_PX = 10/);
  assert.match(selectionSource, /const MIN_SELECTION_SIZE = 3/);
  assert.match(selectionSource, /const AREA_SELECTION_ANTS_ENABLED = false/);
  assert.match(selectionSource, /namespace\.areaSelection = \{/);
  assert.match(selectionSource, /function getDocumentScreenRect\(\)/);
  assert.match(selectionSource, /overlayCache: \{/);
  assert.match(selectionSource, /function markOverlayRegionDirty\(\)/);
  assert.match(selectionSource, /function markOverlayScreenDirty\(\)/);
  assert.match(selectionSource, /function strokeCachedBoundary\(ctx, dashOffset = 0, isAnimated = false\)/);
  assert.match(selectionSource, /if \(!isAnimated\) \{[\s\S]*ctx\.setLineDash\(\[6, 6\]\);[\s\S]*ctx\.lineDashOffset = 0;[\s\S]*strokePath\(\);[\s\S]*return;/);
  assert.match(selectionSource, /function isOverlayAnimationPaused\(\) \{/);
  assert.match(selectionSource, /brushEngine\?\.isDrawing === true/);
  assert.match(selectionSource, /brushEngine\?\.isPanning === true/);
  assert.match(selectionSource, /smudgeEngine\?\.isDragging === true/);
  assert.match(selectionSource, /const dashOffset = isOverlayAnimationPaused\(\)/);
  assert.match(selectionSource, /function handleOverlayCameraChange\(\) \{/);
  assert.match(selectionSource, /function rebuildOverlayRegionCache\(\)/);
  assert.match(selectionSource, /function rebuildOverlayScreenCache\(documentRect\)/);
  assert.match(selectionSource, /function drawSelectionShade\(overlay, viewportRect, dpr\)/);
  assert.match(selectionSource, /function drawOverlayBoundaryFrame\(overlay, viewportRect, dpr\)/);
  assert.match(selectionSource, /shadeCanvas\.className = "editor-area-selection-canvas editor-area-selection-shade-canvas"/);
  assert.match(selectionSource, /antsCanvas\.className = "editor-area-selection-canvas editor-area-selection-ants-canvas"/);
  assert.match(selectionSource, /overlay\.append\(shadeCanvas, antsCanvas\)/);
  assert.match(selectionSource, /state\.overlayCache\.boundarySegmentsDoc = state\.region\?\.getBoundarySegments\?\.\(\) \|\| \[\]/);
  assert.match(selectionSource, /const boundaryPath = typeof Path2D === "function" \? new Path2D\(\) : null/);
  assert.match(selectionSource, /if \(AREA_SELECTION_ANTS_ENABLED\) \{/);
  assert.match(selectionSource, /strokeLassoPath\(ctx, AREA_SELECTION_ANTS_ENABLED \? dashOffset : 0\)/);
  assert.match(selectionSource, /drawSelectionShade\(overlay, viewportRect, dpr\)/);
  assert.match(selectionSource, /drawOverlayBoundaryFrame\(overlay, viewportRect, dpr\)/);
  assert.match(selectionSource, /ctx\.globalCompositeOperation = "destination-out";[\s\S]*ctx\.fillStyle = "#000000";/);
  assert.match(selectionSource, /state\.region = cloneRegion\(region\)/);
  assert.match(selectionSource, /namespace\.activeAreaSelectionRects = cloneRects\(state\.rects\)/);
  assert.match(selectionSource, /function createColorRangeRegion\(source, sample, tolerance\)/);
  assert.match(selectionSource, /function selectColorRangeAt\(point\)/);
  assert.match(selectionSource, /function createLayerAlphaRegion\(source, alphaThreshold = COLOR_RANGE_MIN_ALPHA\)/);
  assert.match(selectionSource, /function selectLayerAlpha\(layerId, options = \{\}\)/);
  assert.match(selectionSource, /canSelectLayerAlpha,/);
  assert.match(selectionSource, /selectLayerAlpha,/);
  assert.match(selectionSource, /createRegionFromRows\(rows\)/);
  assert.match(selectionSource, /applyRegionOperation\(beforeRegion, sampledRegion, state\.operationMode\)/);
  assert.match(selectionSource, /source: options\.source \|\| "area-selection-layer-alpha-commit"/);
  assert.match(selectionSource, /setColorRangeSampleColor\(rgbToHexColor\(sample\.r, sample\.g, sample\.b\)/);
  assert.match(selectionSource, /getRegionSnapshot/);
  assert.match(selectionSource, /host\?\.appendChild\(overlay\)/);
  assert.match(selectionSource, /const pointerTarget = canvas\?\.closest\?\.\("\.editor-stage"\) \|\| canvas/);
  assert.match(selectionSource, /pointerTarget\.addEventListener\("pointerdown", handlePointerDown, true\)/);
  assert.match(selectionSource, /pointerTarget\.addEventListener\("wheel", handleOverlayActivity, true\)/);
  assert.match(selectionSource, /window\.addEventListener\("cbo:camera-change", handleOverlayCameraChange\)/);
  assert.match(selectionSource, /window\.addEventListener\("resize", handleOverlayResize\)/);
  assert.match(topToolbarSource, /data-area-selection-operation-toolbar/);
  assert.match(topToolbarSource, /data-area-selection-operation="replace"/);
  assert.match(topToolbarSource, /data-area-selection-operation="add"/);
  assert.match(topToolbarSource, /data-area-selection-operation="subtract"/);
  assert.match(topToolbarSource, /data-color-range-tolerance-control/);
  assert.match(topToolbarSource, /data-color-range-tolerance-input/);
  assert.match(topToolbarSource, /REPLACE SELECTION 1/);
  assert.match(topToolbarSource, /ADD TO SELECTION 2/);
  assert.match(topToolbarSource, /SUBTRACT FROM SELECTION 3/);
  assert.match(topToolbarSource, /window\.CBO\.areaSelection\?\.setOperationMode\?\./);
  assert.match(topToolbarSource, /window\.CBO\.areaSelection\?\.setColorRangeTolerance\?\./);
  assert.match(topToolbarSource, /window\.CBO\.areaSelection\?\.getOperationMode\?\./);
  assert.match(topToolbarSource, /window\.CBO\.areaSelection\?\.getColorRangeTolerance\?\./);
  assert.match(topToolbarSource, /cbo:area-selection-operation-change/);
  assert.match(topToolbarSource, /cbo:color-range-tolerance-change/);
  assert.match(topToolbarSource, /cbo:color-range-sample-change/);
  assert.match(topToolbarSource, /toolMode === "selection-rect" \|\| toolMode === "selection-circle" \|\| toolMode === "selection-lasso" \|\| toolMode === "selection-polygon-lasso"/);
  assert.match(topToolbarSource, /toolMode === "selection-color-range"/);
  assert.match(topToolbarSource, /showAreaSelectionOperationToolbar\(isAreaSelection\)/);
  assert.match(topToolbarSource, /showColorRangeToleranceControl\(isColorRange\)/);
  assert.match(topToolbarCss, /\.area-selection-operation-toolbar/);
  assert.match(topToolbarCss, /\.area-selection-operation-button/);
  assert.match(topToolbarCss, /\.area-selection-tolerance-control/);
  assert.match(topToolbarCss, /--color-range-tolerance-progress/);
  assert.match(layoutSource, /\.editor-area-selection-overlay/);
  assert.match(layoutSource, /position: absolute/);
  assert.match(layoutSource, /z-index: 3/);
  assert.match(layoutSource, /\.editor-area-selection-canvas/);
  assert.match(layoutSource, /inset: 0/);
  assert.match(layoutSource, /display: block/);
});

test("brush and fill constrain raster edits to an active area selection", () => {
  const brushSource = readRepoFile("js", "brush-engine.js");
  const rendererSource = readRepoFile("js", "document", "document-renderer.js");
  const fillSource = readRepoFile("js", "color-fill.js");
  const smudgeSource = readRepoFile("js", "smudge-engine.js");

  assert.match(brushSource, /getActiveAreaSelectionCoverageRects\(rect\)/);
  assert.match(brushSource, /namespace\.getActiveDocumentArtboardRect\?\.\(\{ layerId \}\)/);
  assert.match(brushSource, /namespace\.areaSelection\.getIntersectingRects\?\.\(clippedRect\)/);
  assert.match(brushSource, /const selectionCoverageRects = this\.getActiveAreaSelectionCoverageRects\(strokeRect\)/);
  assert.match(brushSource, /const hasSelectionCoverage = Array\.isArray\(selectionCoverageRects\) && selectionCoverageRects\.length > 0/);
  assert.match(brushSource, /const hasEmptySelectionCoverage = Array\.isArray\(selectionCoverageRects\) && selectionCoverageRects\.length === 0/);
  assert.match(brushSource, /this\.getBoundsForDocumentRects\(selectionCoverageRects\)/);
  assert.match(brushSource, /filterTilePatchRectsToCoverage\(/);
  assert.match(brushSource, /ensureRasterTargetsForPaintRect\?\.\(layerId, effectiveStrokeRect/);
  assert.match(brushSource, /beginRasterTileHistory\?\.\(layerId, effectiveStrokeRect/);
  assert.match(brushSource, /activeStrokeClipRect: namespace\.areaSelection\?\.hasSelection\?\.\(\)/);
  assert.match(brushSource, /activeStrokeClipRects: this\.getActiveAreaSelectionCoverageRects\(this\.strokeBufferRect\)/);
  assert.match(brushSource, /function[\s\S]*getActiveAreaSelectionMask\(rect\) \{|getActiveAreaSelectionMask\(rect\) \{/);
  assert.match(brushSource, /region\?\.createMaskPixels\?\.\(rect\)/);
  assert.match(brushSource, /activeStrokeSelectionMask: this\.currentStrokeTool === "eraser"/);
  assert.match(rendererSource, /const activeStrokeClipRects = Array\.isArray\(options\.activeStrokeClipRects\) && activeStrokeRect/);
  assert.match(rendererSource, /uniform sampler2D u_selectionClipTexture/);
  assert.match(rendererSource, /uniform float u_selectionClipMode/);
  assert.match(rendererSource, /eraseAlpha \*= selectionAlpha/);
  assert.match(rendererSource, /getActiveStrokeSelectionClipTexture\(mask\)/);
  assert.match(rendererSource, /options\.activeStrokeClipRect \|\|[\s\S]*activeStrokeClipRects/);
  assert.match(rendererSource, /withActiveStrokeClip\(\(\) => \{/);
  assert.match(rendererSource, /clipRects\.forEach\(\(clipRect\) => \{/);
  assert.match(rendererSource, /uniform vec4 u_maskClipRect/);
  assert.match(rendererSource, /uniform vec4 u_maskClipRects\[32\]/);
  assert.match(rendererSource, /uniform int u_maskClipRectCount/);
  assert.match(rendererSource, /function[\s\S]*setMaskClipUniforms|const setMaskClipUniforms = \(uniformSet, clipRect = null, clipRects = null\) =>/);
  assert.match(rendererSource, /let currentMaskClipRect = null/);
  assert.match(rendererSource, /let currentMaskClipRects = null/);
  assert.match(rendererSource, /currentMaskClipRects = activeStrokeClipRects \|\| null/);
  assert.match(rendererSource, /const activeStrokeNeedsScratchMerge = Boolean\([\s\S]*options\.activeStrokeTexture[\s\S]*activeStrokeMode !== "eraser"[\s\S]*activeStrokeLayer[\s\S]*!activeStrokeHasClip[\s\S]*activeStrokeLayerUsesAdvancedCompositing/);
  assert.match(brushSource, /targetCoverageRects\.forEach\(\(selectionTargetRect\) => \{/);
  assert.match(brushSource, /gl\.enable\(gl\.SCISSOR_TEST\)/);
  assert.match(smudgeSource, /getActiveAreaSelectionCoverageRects\(bounds\) \{/);
  assert.match(smudgeSource, /namespace\.getActiveDocumentArtboardRect\?\.\(\{/);
  assert.match(smudgeSource, /namespace\.areaSelection\?\.hasSelection\?\.\(\)/);
  assert.match(smudgeSource, /namespace\.areaSelection\.getIntersectingRects\?\.\(clippedBounds\)/);
  assert.match(smudgeSource, /selectionCoverageRects\.forEach\(\(coverageRect\) => \{/);
  assert.match(fillSource, /namespace\.areaSelection\.getRegionSnapshot\?\.\(\)/);
  assert.match(fillSource, /getActiveFillArtboardRect\(writableLayer\.layerId\)/);
  assert.match(fillSource, /dirtyRect = intersectRects\(dirtyRect, activeArtboardRect\)/);
  assert.match(fillSource, /selectionRegion\.containsPoint\?\.\(docX, docY\) === true/);
  assert.match(fillSource, /dirtyRect = selectionRegion\.intersectBounds\?\.\(dirtyRect\) \|\| null/);
  assert.match(fillSource, /tilePatchRects: options\.tilePatchRects|tilePatchRects,/);
});

test("delete and escape shortcuts operate on the active area selection", () => {
  const selectionSource = readRepoFile("js", "area-selection-tool.js");

  assert.match(selectionSource, /function deleteSelectionPixels\(\)/);
  assert.match(selectionSource, /function pushSelectionHistory\(beforeRegion, afterRegion, options = \{\}\) \{/);
  assert.match(selectionSource, /type: "selection"/);
  assert.match(selectionSource, /history\.push\(\{/);
  assert.match(selectionSource, /restoreSelectionHistoryRegion\(before, "history-undo-area-selection"\)/);
  assert.match(selectionSource, /restoreSelectionHistoryRegion\(after, "history-redo-area-selection"\)/);
  assert.match(selectionSource, /const beforeRegion = cloneRegion\(options\.historyBeforeRegion \|\| state\.region\)/);
  assert.match(selectionSource, /historyBeforeRegion: state\.baseRegion/);
  assert.match(selectionSource, /history: false/);
  assert.match(selectionSource, /selectionHistory === false/);
  assert.match(selectionSource, /!\/commit\|escape\|clear\/\.test\(source\)/);
  assert.match(selectionSource, /beginRasterTileHistory\?\.\(layerId, rect,/);
  assert.match(selectionSource, /key === "Escape"/);
  assert.match(selectionSource, /key === "Escape"[\s\S]*event\.stopPropagation\(\);[\s\S]*clear\(\{ source: "area-selection-escape" \}\);[\s\S]*if \(isEditableTarget\(event\.target\)\)/);
  assert.match(selectionSource, /event\.key !== "Delete" && event\.key !== "Backspace"/);
});

test("copy and paste shortcuts duplicate the selected pixels with an offset", () => {
  const selectionSource = readRepoFile("js", "area-selection-tool.js");

  assert.match(selectionSource, /const PASTE_OFFSET_PX = 60/);
  assert.match(selectionSource, /function copySelectionPixels\(\)/);
  assert.match(selectionSource, /const sourceTarget = renderer\.rasterTargetsByLayerId\?\.get\?\.\(layerId\)/);
  assert.match(selectionSource, /createRasterSnapshot\?\.\(sourceTarget, selectionRect, "area-selection-copy"\)/);
  assert.match(selectionSource, /snapshots: validSnapshots/);
  assert.match(selectionSource, /function pasteSelectionPixels\(\)/);
  assert.match(selectionSource, /x: item\.rect\.x \+ PASTE_OFFSET_PX/);
  assert.match(selectionSource, /y: item\.rect\.y \+ PASTE_OFFSET_PX/);
  assert.match(selectionSource, /layerModel\.ensureActivePaintLayer\(\{/);
  assert.match(selectionSource, /history: false/);
  assert.match(selectionSource, /finalizeRasterEditHistoryEntry\?\.\(layerId, baseEntry,/);
  assert.match(selectionSource, /copyRasterTargetRectIntoTarget\?\.\(sourceTarget, patchRect, target\)/);
  assert.match(selectionSource, /clear\(\{ source: "area-selection-paste" \}\)/);
  assert.match(selectionSource, /shortcutKey === "c"/);
  assert.match(selectionSource, /shortcutKey === "v"/);
  assert.match(selectionSource, /copySelectionPixels,/);
  assert.match(selectionSource, /pasteSelectionPixels,/);
});

test("rect selection drag supports shift square and alt center modifiers", () => {
  const selectionSource = readRepoFile("js", "area-selection-tool.js");

  assert.match(selectionSource, /function normalizeRectFromPoints\(startPoint, endPoint, options = \{\}\)/);
  assert.match(selectionSource, /const fromCenter = options\.fromCenter === true/);
  assert.match(selectionSource, /const forceSquare = options\.forceSquare === true/);
  assert.match(selectionSource, /if \(fromCenter\) \{/);
  assert.match(selectionSource, /if \(forceSquare\) \{/);
  assert.match(selectionSource, /Math\.min\([\s\S]*Math\.max\(radiusX, radiusY\),[\s\S]*startX - minBoundX,[\s\S]*maxBoundX - startX,[\s\S]*startY - minBoundY,[\s\S]*maxBoundY - startY/);
  assert.match(selectionSource, /function getSelectionDragOptions\(event\) \{/);
  assert.match(selectionSource, /forceSquare: event\.shiftKey === true/);
  assert.match(selectionSource, /fromCenter: event\.altKey === true/);
  assert.match(selectionSource, /function normalizeOperationMode\(mode\) \{/);
  assert.match(selectionSource, /function setOperationMode\(mode, options = \{\}\) \{/);
  assert.match(selectionSource, /function getOperationMode\(\) \{/);
  assert.match(selectionSource, /function isRectToolActive\(\) \{/);
  assert.match(selectionSource, /state\.activeToolMode === RECT_TOOL_MODE/);
  assert.match(selectionSource, /function isCircleToolActive\(\) \{/);
  assert.match(selectionSource, /state\.activeToolMode === CIRCLE_TOOL_MODE/);
  assert.match(selectionSource, /function isLassoToolActive\(\) \{/);
  assert.match(selectionSource, /state\.activeToolMode === LASSO_TOOL_MODE/);
  assert.match(selectionSource, /function isPolygonLassoToolActive\(\) \{/);
  assert.match(selectionSource, /state\.activeToolMode === POLYGON_LASSO_TOOL_MODE/);
  assert.match(selectionSource, /function isColorRangeToolActive\(\) \{/);
  assert.match(selectionSource, /state\.activeToolMode === COLOR_RANGE_TOOL_MODE/);
  assert.match(selectionSource, /function isPolygonLassoInProgress\(\) \{/);
  assert.match(selectionSource, /function isAreaSelectionToolActive\(\) \{/);
  assert.match(selectionSource, /isPolygonLassoToolActive\(\)/);
  assert.match(selectionSource, /isColorRangeToolActive\(\)/);
  assert.match(selectionSource, /function getActiveSelectionShape\(\) \{/);
  assert.match(selectionSource, /isCircleToolActive\(\) \? "ellipse" : "rect"/);
  assert.match(selectionSource, /function createRegionFromEllipse\(rect\) \{/);
  assert.match(selectionSource, /baseRegion\?\.addEllipse\?\.|baseRegion\?\.subtractEllipse\?\./);
  assert.match(selectionSource, /function applyLassoOperation\(baseSelection, points, mode = "replace"\) \{/);
  assert.match(selectionSource, /baseRegion\?\.addPolygon\?\.\(points\)/);
  assert.match(selectionSource, /baseRegion\?\.subtractPolygon\?\.\(points\)/);
  assert.match(selectionSource, /function appendLassoPoint\(point\) \{/);
  assert.match(selectionSource, /function beginPolygonLasso\(point\) \{/);
  assert.match(selectionSource, /function commitPolygonLasso\(source = "area-selection-polygon-lasso-commit"\) \{/);
  assert.match(selectionSource, /function removeLastPolygonLassoPoint\(\) \{/);
  assert.match(selectionSource, /function handlePolygonLassoPointerDown\(event, point\) \{/);
  assert.match(selectionSource, /function strokeLassoPath\(ctx, dashOffset = 0\) \{/);
  assert.match(selectionSource, /state\.overlayCache\.coveragePath/);
  assert.match(selectionSource, /ctx\.fill\(state\.overlayCache\.coveragePath\)/);
  assert.match(selectionSource, /const fillDeviceRect = \(rect\) => \{/);
  assert.match(selectionSource, /Math\.floor\(rect\.left \* dpr\)/);
  assert.match(selectionSource, /function buildContinuousBoundaryPaths\(segments\) \{/);
  assert.match(selectionSource, /buildContinuousBoundaryPaths\(state\.overlayCache\.boundarySegmentsDoc\)/);
  assert.match(selectionSource, /boundaryPath\.closePath\(\)/);
  assert.match(selectionSource, /cbo:area-selection-operation-change/);
  assert.match(selectionSource, /state\.baseRegion = getRegionSnapshot\(\)/);
  assert.match(selectionSource, /state\.dragOperationMode = state\.operationMode/);
  assert.match(selectionSource, /applySelectionOperation\(/);
  assert.match(selectionSource, /normalizeRectFromPoints\(state\.startPoint, point, getSelectionDragOptions\(event\)\)/);
  assert.match(selectionSource, /updateOverlay\(\{ shadeDirty: false \}\)/);
  assert.match(selectionSource, /source: "area-selection-lasso-commit"/);
  assert.match(selectionSource, /visualPolygonPoints: operationMode === "replace" \? points : null/);
  assert.match(selectionSource, /event\.key === "Enter"/);
  assert.doesNotMatch(selectionSource, /visualPolygonPoints: state\.dragOperationMode === "replace" \? state\.lassoPoints : null/);
  assert.match(selectionSource, /state\.lassoPoints = \[\]/);
  assert.match(selectionSource, /state\.baseRegion = null/);
  assert.match(selectionSource, /setOperationMode\("replace", \{ source: "area-selection-shortcut" \}\)/);
  assert.match(selectionSource, /setOperationMode\("add", \{ source: "area-selection-shortcut" \}\)/);
  assert.match(selectionSource, /setOperationMode\("subtract", \{ source: "area-selection-shortcut" \}\)/);
  assert.match(selectionSource, /getOperationMode,/);
  assert.match(selectionSource, /setOperationMode,/);
  assert.doesNotMatch(selectionSource, /function getSelectionMode\(event\)/);
});
